# Generated by Django 4.0.5 on 2022-06-27 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemonstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'PokemonType',
                'verbose_name_plural': 'PokemonTypes',
            },
        ),
        migrations.AlterModelOptions(
            name='pokemonstats',
            options={'verbose_name': 'PokemonStat', 'verbose_name_plural': 'PokemonStats'},
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Types', to='pokedex.pokemontype'),
        ),
    ]
